# Generated by Django 5.2.7 on 2026-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(default='XYZ', max_length=100),
            preserve_default=False,
        ),
    ]
