# Generated by Django 5.2.7 on 2026-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tickets_booked_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_file',
            field=models.FileField(default='', upload_to='tickets/'),
            preserve_default=False,
        ),
    ]
