# Generated by Django 5.2.7 on 2026-01-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tickets_ticket_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
