# Generated by Django 5.2.7 on 2026-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tickets_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
