# Generated by Django 5.2.7 on 2026-02-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tickets_amount_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=200)),
                ('reservation_file', models.FileField(upload_to='reservations/')),
                ('description', models.TextField()),
                ('date_of_reservation', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_type', models.CharField(max_length=100)),
                ('booked_through', models.CharField(max_length=100)),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='reservation_thumbnails/')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
