# Generated by Django 5.2.7 on 2026-02-17 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tickets_amount_paid_reservations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD - United States Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - Pound Sterling'), ('INR', 'INR - Indian Rupee'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('JPY', 'JPY - Japanese Yen'), ('CNY', 'CNY - Chinese Yuan'), ('SGD', 'SGD - Singapore Dollar'), ('CHF', 'CHF - Swiss Franc'), ('NZD', 'NZD - New Zealand Dollar'), ('ZAR', 'ZAR - South African Rand'), ('SEK', 'SEK - Swedish Krona'), ('NOK', 'NOK - Norwegian Krone'), ('DKK', 'DKK - Danish Krone'), ('BRL', 'BRL - Brazilian Real'), ('MXN', 'MXN - Mexican Peso'), ('RUB', 'RUB - Russian Ruble'), ('HKD', 'HKD - Hong Kong Dollar'), ('KRW', 'KRW - South Korean Won'), ('AED', 'AED - United Arab Emirates Dirham'), ('ARS', 'ARS - Argentine Peso'), ('BDT', 'BDT - Bangladeshi Taka'), ('BGN', 'BGN - Bulgarian Lev'), ('BHD', 'BHD - Bahraini Dinar'), ('BND', 'BND - Brunei Dollar'), ('BOB', 'BOB - Bolivian Boliviano'), ('BWP', 'BWP - Botswana Pula'), ('BYN', 'BYN - Belarusian Ruble'), ('CLP', 'CLP - Chilean Peso'), ('COP', 'COP - Colombian Peso'), ('CRC', 'CRC - Costa Rican Colón'), ('CZK', 'CZK - Czech Koruna'), ('DOP', 'DOP - Dominican Peso'), ('EGP', 'EGP - Egyptian Pound'), ('ETB', 'ETB - Ethiopian Birr'), ('GHS', 'GHS - Ghanaian Cedi'), ('GTQ', 'GTQ - Guatemalan Quetzal'), ('HUF', 'HUF - Hungarian Forint'), ('IDR', 'IDR - Indonesian Rupiah'), ('ILS', 'ILS - Israeli New Shekel'), ('IQD', 'IQD - Iraqi Dinar'), ('IRR', 'IRR - Iranian Rial'), ('JOD', 'JOD - Jordanian Dinar'), ('KES', 'KES - Kenyan Shilling'), ('KWD', 'KWD - Kuwaiti Dinar'), ('KZT', 'KZT - Kazakhstani Tenge'), ('LAK', 'LAK - Lao Kip'), ('LKR', 'LKR - Sri Lankan Rupee'), ('MAD', 'MAD - Moroccan Dirham'), ('MDL', 'MDL - Moldovan Leu'), ('MXV', 'MXV - Mexican Unidad de Inversion (UDI)'), ('MNT', 'MNT - Mongolian Tögrög'), ('MUR', 'MUR - Mauritian Rupee'), ('MVR', 'MVR - Maldivian Rufiyaa'), ('MWK', 'MWK - Malawian Kwacha'), ('MYR', 'MYR - Malaysian Ringgit'), ('NGN', 'NGN - Nigerian Naira'), ('NPR', 'NPR - Nepalese Rupee'), ('OMR', 'OMR - Omani Rial'), ('PAB', 'PAB - Panamanian Balboa'), ('PEN', 'PEN - Peruvian Sol'), ('PHP', 'PHP - Philippine Peso'), ('PKR', 'PKR - Pakistani Rupee'), ('PLN', 'PLN - Polish Złoty'), ('PYG', 'PYG - Paraguayan Guaraní'), ('QAR', 'QAR - Qatari Riyal'), ('RON', 'RON - Romanian Leu'), ('RSD', 'RSD - Serbian Dinar'), ('SHP', 'SHP - Saint Helena Pound'), ('SOS', 'SOS - Somali Shilling'), ('SRD', 'SRD - Surinamese Dollar'), ('SYP', 'SYP - Syrian Pound'), ('THB', 'THB - Thai Baht'), ('TND', 'TND - Tunisian Dinar'), ('TRY', 'TRY - Turkish Lira'), ('TTD', 'TTD - Trinidad and Tobago Dollar'), ('TWD', 'TWD - New Taiwan Dollar'), ('UAH', 'UAH - Ukrainian Hryvnia'), ('UGX', 'UGX - Ugandan Shilling'), ('UYU', 'UYU - Uruguayan Peso'), ('UZS', 'UZS - Uzbekistani Som'), ('VND', 'VND - Vietnamese Dong'), ('VUV', 'VUV - Vanuatu Vatu'), ('XAF', 'XAF - Central African CFA Franc'), ('XCD', 'XCD - East Caribbean Dollar'), ('XOF', 'XOF - West African CFA Franc'), ('XPF', 'XPF - CFP Franc'), ('YER', 'YER - Yemeni Rial'), ('ZMW', 'ZMW - Zambian Kwacha'), ('ZWL', 'ZWL - Zimbabwean Dollar')], default='INR', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
