# Generated by Django 5.2.7 on 2026-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tickets_miles_traveled_tickets_nights_stayed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='miles_traveled',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='nights_stayed',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='triprep_score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='miles_traveled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nights_stayed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='triprep_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=5, null=True),
        ),
    ]
