# Generated by Django 5.2.7 on 2026-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_tickets_miles_traveled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
