# Generated by Django 5.2.7 on 2026-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reservations_nights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nights_stayed',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='triprep_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
    ]
