# Generated by Django 6.0.6 on 2026-06-09 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_userprofile_nights_stayed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date_of_trip', models.DateField()),
                ('end_date_of_trip', models.DateField()),
                ('trip_created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_type', models.CharField(choices=[('business', 'Business'), ('leisure', 'Leisure'), ('family', 'Family'), ('couple', 'Couple'), ('group', 'Group'), ('solo', 'Solo'), ('personal', 'Personal')], default='personal', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='trip_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.trips'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='trip_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.trips'),
        ),
    ]
