# Generated by Django 6.0.6 on 2026-06-28 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_trips_reservations_trip_link_tickets_trip_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'ordering': ['-trip_created_at']},
        ),
        migrations.AddConstraint(
            model_name='trips',
            constraint=models.UniqueConstraint(fields=('user', 'trip_name'), name='unique_trip_name_per_user'),
        ),
    ]
